FROM opencpu/ubuntu-18.04 


RUN Rscript -e "install.packages(c('devtools','tidyr','dplyr','purrr','httr','RSQLite'))"

ARG rstudio_pass

#change default password for user: opencpu
RUN \
  echo "opencpu:$rstudio_pass" | chpasswd

#allow DB access from package (may not be required?)
#might also need to sudo chown www-data /ctsgetr/inst/.
RUN mkdir ctsgetr
RUN echo -e "/ctsgetr/ rw,\n/ctsgetr/** rwkmix,\n" >> /etc/apparmor.d/opencpu.d/custom
  


COPY ./ ./ctsgetr
RUN Rscript -e "devtools::install('ctsgetr',upgrade='never')"