version: '2.0'

services:
    ctsgetr:
      build: 
        context: .
        dockerfile: dockerfile
        args:
          - rstudio_pass=${rstudio_pass}
      image: dgrapov/ctsgetr:latest
      container_name: ctsgetr
        
      environment:
        - ctsgetr_db=/ctsgetr/ctsgetr.sqlite # set this to mounted version else use internal
      
      ports:
        - "80:80"

     