version: '2.0'

services:
    ctsgetr:
      build: 
        context: .
        dockerfile: dockerfile_custom
        args:
          - rstudio_pass=${rstudio_pass}
      image: dgrapov/ctsgetr:latest
      container_name: ctsgetr
      
      volumes:
        - ${ctsgetr_db_mount}:/ctsgetrdb/
        
      environment:
        - ctsgetr_db=/ctsgetr/inst/ctsgetr.sqlite # set this to mounted version else use internal
      
      ports:
        - "80:80"

     